version: '3'

services:
  #PHP Service
  app_service:
    build: ./php/
    container_name: app_service
    volumes:
      - ./src:/var/www
    networks:
      - service-network

  #Nginx Service
  nginx_service:
    image: nginx:alpine
    container_name: nginx_service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - service-network

  #Postgres Service
  pgsql_service:
    container_name: pgsql_service
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
    networks:
      - service-network

#Docker Networks
networks:
  service-network:
    driver: bridge
