version: "3"

services:
  #PHP Service
  php_entrepreneur_service:
    build: ./php/
    container_name: php_entrepreneur_service
    depends_on:
      - pgsql_entrepreneur_service
    volumes:
      - ./src:/var/www
    networks:
      - service-entrepreneur-network

  #Nginx Service
  nginx_entrepreneur_service:
    image: nginx:alpine
    container_name: nginx_entrepreneur_service
    depends_on:
      - php_entrepreneur_service
      - pgsql_entrepreneur_service
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      service-entrepreneur-network:
        aliases:
          - backend.entrepreneur.com

  #Postgres Service
  pgsql_entrepreneur_service:
    container_name: pgsql_entrepreneur_service
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
    networks:
      - service-entrepreneur-network

#Docker Networks
networks:
  service-entrepreneur-network:
    driver: bridge
